name: Go-test

on:
  push:
    branches-ignore:
      - develog
  pull_request:
    branches: [ "develog" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 🔹 确保 Git 历史完整

    - name: Fix HEAD issue
      run: git checkout $(git rev-parse HEAD)  # 🔹 确保 HEAD 有效
  
    - name: Fetch all branches
      run: git fetch --prune  # ✅ 移除 --unshallow，避免错误
    
    - name: gitlint
      run: cp scripts/gitlint_ub_x86-64 /usr/local/bin/gitlint && make gitlint

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 🔹 确保 Git 历史完整

    - name: env check
      run: make check